#!/usr/bin/env bash
#This code will print numbers from 1 to 100, but will print fizz on multiples of 3, buzz on multiples of 5 and fizzbuzz on multiples of 3 and 5
i=1

while [ $i -le 100 ]
do
    f=$(( i % 3 ))
    b=$(( i % 5 ))

    if [ $f -eq 0 ] && [ $b -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $f -eq 0 ]
    then
	echo "Fizz"
    elif [ $b -eq 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi


    i=$(( i + 1 ))
    done
	 
