#!/usr/bin/env bash
##This will print Holberton school 9 times, with Hi being printed on the 9th line
i=0
while [ $i -le 9 ]
do
echo "Holberton School"
((i++))
if [ $i == 8 ]
then
    echo "Hi"
((i++))
fi
done
exit 0
