#!/usr/bin/env bash
#This will print Holberton school 10 times, with Hi being printed after the 9th line
i=0
while [ $i -lt 10 ]
do
echo "Holberton School"
if [ $i == 8 ]
then
    echo "Hi"
fi
((i++))
done
