#!/usr/bin/env bash
i=0
while [ $i -le 9 ]
do
    echo "Holberton School"
    ((i++))
if [ $i == 3 ]
then
    echo "bad luck"
    ((i++))
elif [ $i == 7 ]
then
    echo "good luck"
    ((i++))
else
    echo "Holberton School"
    ((i++))
    fi
done
exit 0
