#!/usr/bin/env bash
##This code will print holberton school 8 times with bad luck being printed on the 4th line and good luck printed on the 8th line
i=0
while [ $i -le 9 ]
do
    echo "Holberton School"
    ((i++))
if [ $i == 3 ]
then
    echo "bad luck"
    ((i++))
elif [ $i == 7 ]
then
    echo "good luck"
    ((i++))
else
    echo "Holberton School"
    ((i++))
    fi
done
exit 0
