#!/usr/bin/env bash
##This code will print the variable "i" except on certain increments, it will print the statements
i=1
while [ $i -le 20 ]
do
case $i in
4) echo -e "$i\nbad luck from China" ;;
9) echo -e "$i\nbad luck from Japan" ;;
17) echo -e "$i\nbad luck from Italy" ;;
*) echo -e $i;;
esac
((i++))
done
