#!/usr/bin/env bash
##This code will print the variable "i" except on certain increments, it will print the statements
i=1
while [ $i -le 20 ]
do
    echo $i
        ((i++))
	    case $i in
	            4) echo 'bad luck from China' ;;
		            9) echo 'bad luck from Japan' ;;
			            17) echo 'bad luck from Italy' ;;
				                    esac
						                  done
								                  exit 0
