#!/usr/bin/env bash
#This code will print i until it increments to the first hour, then it will reset the minutes and repeat until hour 12 is reached
i=1
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    while [ $i -le 59 ]
    do
	echo "$i"
	((i++))
    done
    ((h++))
    i=1
done
