#!/usr/bin/env bash
##This code will check for the existence of a file "holbertonschool" and will make a statment based on if it does or not
if [ -e holbertonSchool ]
   then
	echo "holbertonschool file exists"
	else
	echo "holbertonschool file does not exist"

if [ -e holbertonschool ] && [ -s holbertonschool ]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"

if [ -f holbertonscool ]
then
echo "holbertonschool file is a regular file"
fi
fi
fi
exit 0
