#!/usr/bin/env bash
#This code will check for the existence of a file "holbertonschool" and will make a statment based on if it does or not
if [ -e holbertonschool ]
then
echo "holbertonschool file exists"
if [ -s holbertonschool ]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi
if [ -f holbertonschool ]
then
    echo "holbertonschool file is a regular file"
fi
else
echo "holbertonschool file does not exist"
fi
